### PR TITLE
compare lowered headers

### PR DESCRIPTION
**Pull request by alexandrim0**
compare lowered headers because of some clients fails upload

### CODE REVIEW

**Review by antonheryanto — APPROVED** [review]
Thank you

**Comment by alexandrim0** [comment]
Will you publish it to luarocks or\and to OPM?

**Comment by antonheryanto** [comment]
will do. thanks for the remainder

**Comment by antonheryanto** [comment]
uploaded to [opm](https://opm.openresty.org/package/antonheryanto/lua-resty-post/)

**Comment by alexandrim0** [comment]
Thank you!

**Pull request merged**
